server:
  port: 8052
  servlet:
    context-path: /shop-server/api
spring:
  application:
    name: shop
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
  datasource:
    platform: org.hibernate.dialect.PostgreSQLDialect
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/shop
    username: postgres
    password: postgres
  mail:
    host: smtp.gmail.com
    port: 587
    username: shotartinovcourcemanualqa@gmail.com
    password: rtxshvkmgxlkuazm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    sender:
      email: shop-artinov-manual-qa-no-replay@shop.ua
      text: no-reply
